version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - javascript
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /src/dashboard
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dashboard
    groups:
      dashboard-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions-all:
        patterns:
          - "*"
