import { resolve, basename } from "node:path";
import { existsSync, mkdirSync, rmSync } from "node:fs";
import { loadConfig } from "../../config.js";
import { routeTask } from "../../core/router.js";
import { runClaudePipe } from "../../integrations/claude-p/claude-pipe.js";
import { runOpencodePipe } from "../../integrations/opencode/opencode-pipe.js";
import { getDb } from "../../storage/db.js";
import {
  createWorkItem,
  updateWorkItemStatus,
  rollupWorkItemTokens,
} from "../../storage/repositories/work-items-repo.js";
import {
  createTask,
  updateTaskStatus,
  updateTaskTokens,
} from "../../storage/repositories/tasks-repo.js";
import { insertTelemetryEvent } from "../../storage/repositories/telemetry-repo.js";
import { classifyTask } from "../../core/classifier.js";
import { execSync } from "node:child_process";
import { publishEvent } from "../../api/sse.js";

export function registerRunCommand(program: import("commander").Command) {
  function getDefaultBranch(repoPath: string): string {
    try {
      return execSync(
        `git -C "${repoPath}" symbolic-ref refs/remotes/origin/HEAD --short`,
        { encoding: "utf-8" },
      )
        .trim()
        .replace("origin/", "");
    } catch {
      return "main";
    }
  }

  function createClawBranch(repoPath: string, prompt: string): string {
    const current = execSync(
      `git -C "${repoPath}" rev-parse --abbrev-ref HEAD`,
      { encoding: "utf-8" },
    ).trim();
    const defaultBranch = getDefaultBranch(repoPath);

    if (current !== defaultBranch) return current; // already on a feature branch

    const slug = prompt
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 40);
    const branch = `claw/${slug}-${Date.now().toString(36)}`;
    execSync(`git -C "${repoPath}" checkout -b "${branch}"`, {
      stdio: "inherit",
    });
    console.log(`[git] created branch ${branch}`);
    return branch;
  }

  function autoCommit(
    repoPath: string,
    prompt: string,
    noCommit: boolean,
  ): boolean {
    if (noCommit) {
      console.log("[git] skipping auto-commit due to --no-commit flag");
      return false;
    }

    const statusOutput = execSync(`git -C "${repoPath}" status --porcelain`, {
      encoding: "utf-8",
    });

    if (!statusOutput.trim()) {
      console.log("[git] nothing to commit");
      return false;
    }

    execSync(`git -C "${repoPath}" add -A`, { stdio: "inherit" });

    const commitMessage =
      prompt.length > 72
        ? `claw: ${prompt.substring(0, 72)}`
        : `claw: ${prompt}`;

    execSync(`git -C "${repoPath}" commit -m "${commitMessage}"`, {
      stdio: "inherit",
    });
    console.log("[git] committed changes");
    return true;
  }

  function pushAndCreatePr(
    repoPath: string,
    branch: string,
    prompt: string,
    defaultBranch: string,
  ): string | null {
    try {
      execSync(`git -C "${repoPath}" push -u origin "${branch}"`, {
        stdio: "inherit",
      });
      console.log(`[git] pushed ${branch}`);

      const title =
        prompt.length > 70 ? prompt.substring(0, 67) + "..." : prompt;

      const body = `## Summary\n\nAutomated implementation by Claw Engine.\n\n**Prompt:** ${prompt}\n\n---\n🤖 Generated by [Claw Engine](https://github.com/dougss/claw-engine)`;

      const prUrl = execSync(
        `gh pr create --repo "$(git -C "${repoPath}" remote get-url origin | sed 's/.*github.com[:/]//' | sed 's/.git$//')" --head "${branch}" --base "${defaultBranch}" --title ${JSON.stringify(title)} --body ${JSON.stringify(body)}`,
        { encoding: "utf-8", cwd: repoPath },
      ).trim();
      console.log(`[pr] ${prUrl}`);
      return prUrl;
    } catch (err) {
      console.error(
        "[pr] failed to create PR:",
        err instanceof Error ? err.message : String(err),
      );
      return null;
    }
  }
  program
    .command("run <repo> <prompt>")
    .description("Run a single task directly in a repo")
    .option("--model <model>", "Model to use (overrides router)")
    .option("--delegate", "Force claude -p regardless of complexity")
    .option("--dry-run", "Show plan without executing")
    .option("--max-turns <n>", "Maximum agent turns", parseInt)
    .option("--no-resume", "Disable auto-resume on checkpoint")
    .option("--resume <sessionId>", "Resume a previous session by ID")
    .option("--no-commit", "Skip automatic git commit of changes")
    .option(
      "--pipeline",
      "Use 5-phase pipeline (plan → execute → validate → review → pr)",
    )
    .option("--pr", "Open a PR after pipeline completes (requires --pipeline)")
    .action(
      async (
        repo: string,
        prompt: string,
        opts: {
          model?: string;
          delegate?: boolean;
          dryRun?: boolean;
          maxTurns?: number;
          resume?: boolean | string;
          noResume?: boolean;
          noCommit?: boolean;
          pipeline?: boolean;
          pr?: boolean;
        },
      ) => {
        const GITHUB_RE = /^[a-zA-Z0-9_.-]+\/[a-zA-Z0-9_.-]+$/;
        let isGithubRepo = false;
        let tempDir: string | null = null;
        let repoPath = resolve(repo);

        if (GITHUB_RE.test(repo) && !existsSync(repoPath)) {
          const [owner, repoName] = repo.split("/");
          tempDir = `/tmp/claw-runs/${owner}-${repoName}-${Date.now()}`;
          mkdirSync(tempDir, { recursive: true });
          console.log(
            `[git] cloning https://github.com/${repo}.git → ${tempDir}`,
          );
          execSync(
            `git clone https://github.com/${owner}/${repoName}.git "${tempDir}"`,
            { stdio: "inherit" },
          );
          repoPath = tempDir;
          isGithubRepo = true;
        }

        if (opts.dryRun) {
          console.log(`[dry-run] Would run in ${repoPath}: "${prompt}"`);
          return;
        }

        const config = loadConfig();

        // LLM-based classification — fast Qwen call (~50 tokens, 8s timeout).
        // Falls back to "medium" on error so it never blocks execution.
        let classificationResult: import("../../core/classifier.js").ClassificationResult = { 
          complexity: "medium", 
          title: prompt.slice(0, 60) // fallback title
        };
        if (!opts.delegate) {
          const apiKey =
            process.env[config.providers.alibaba.api_key_env] ?? "";
          if (apiKey) {
            classificationResult = await classifyTask(prompt, {
              apiKey,
              baseUrl: config.providers.alibaba.base_url,
              model: config.models.default,
            });
          }
        }
        const { complexity } = classificationResult;

        const route = routeTask(
          { complexity, description: prompt, fallbackChainPosition: 0 },
          config,
        );

        const effectiveRoute = opts.delegate
          ? {
              ...route,
              provider: "anthropic",
              mode: "delegate" as const,
              reason: "forced claude -p",
            }
          : route;
        const mode = "delegate" as const;

        // Connect Redis for SSE publishing (best-effort, dashboard sees live events)
        let redis: import("ioredis").Redis | null = null;
        try {
          const { Redis } = await import("ioredis");
          redis = new Redis({
            host: config.redis.host,
            port: config.redis.port,
            maxRetriesPerRequest: 1,
            lazyConnect: true,
          });
          await redis.connect();
        } catch {
          redis = null; // SSE publishing is optional
        }

        console.log(`classify → ${complexity}`);
        console.log(
          `routing → ${effectiveRoute.provider} (${effectiveRoute.reason})`,
        );
        console.log(`path    → ${repoPath}\n`);

        // Register this run in the DB so it appears in the dashboard
        const connStr =
          process.env.CLAW_ENGINE_DATABASE_URL ??
          (() => {
            const pw =
              process.env[config.database.password_env] ?? "claw_engine_local";
            return `postgresql://${config.database.user}:${pw}@${config.database.host}:${config.database.port}/${config.database.database}`;
          })();
        let workItemId: string | null = null;
        let taskId: string | null = null;
        let db: ReturnType<typeof getDb> | null = null;
        try {
          db = getDb({ connectionString: connStr });
          const wi = await createWorkItem(db, {
            title: classificationResult.title,
            description: prompt,
            repos: [basename(repoPath)],
            source: "cli:run",
          });
          workItemId = wi.id;
          const branch = `claw-run-${Date.now()}`;
          const task = await createTask(db, {
            workItemId: wi.id,
            repo: basename(repoPath),
            branch,
            description: prompt,
            complexity,
            model: opts.model ?? effectiveRoute.model,
          });
          taskId = task.id;
          await updateWorkItemStatus(db, wi.id, "running");
          await updateTaskStatus(db, task.id, "running");
          void insertTelemetryEvent(db, {
            taskId: task.id,
            eventType: "routing_decision",
            payload: {
              complexity,
              mode,
              reason: effectiveRoute.reason,
            },
          }).catch(() => {});
        } catch {
          // DB tracking is best-effort — don't fail the run if DB is unavailable
          console.error(
            "[warn] could not register run in DB (dashboard won't show it)",
          );
        }

        const finalizeDb = async (wiStatus: string, taskStatus: string) => {
          if (!workItemId || !taskId) return;
          try {
            const db = getDb({ connectionString: connStr });
            await updateTaskStatus(db, taskId, taskStatus);
            await updateWorkItemStatus(db, workItemId, wiStatus);
          } catch {
            /* best-effort */
          }
        };

        if (opts.pipeline) {
          const { runPipeline } = await import("../../core/pipeline.js");
          const { resolve: resolvePath } = await import("node:path");
          const { fileURLToPath } = await import("node:url");
          const __dirname = fileURLToPath(new URL(".", import.meta.url));
          const mcpConfigPath = resolvePath(
            __dirname,
            "../../../config/mcp.json",
          );

          const githubAppId = process.env.CLAW_GITHUB_APP_ID;
          const githubInstallationId = process.env.CLAW_GITHUB_INSTALLATION_ID;
          const githubPrivateKeyPath = process.env.CLAW_GITHUB_PRIVATE_KEY_PATH;
          const githubBotUserId = process.env.CLAW_GITHUB_BOT_USER_ID;

          try {
            const result = await runPipeline({
              repoPath,
              prompt,
              config,
              claudeBin: config.providers.anthropic.binary,
              opencodeBin: config.providers.opencode.binary,
              mcpConfigPath,
              opencodeModel:
                opts.model ??
                config.providers.opencode.default_model ??
                "dashscope/qwen3-coder-plus",
              maxRetries: config.validation.max_retries,
              maxReviewRetries: 2,
              openPr: !!opts.pr,
              githubAppId,
              githubInstallationId,
              githubPrivateKeyPath,
              githubBotUserId,
              onEvent: (event) => {
                if (event.type === "text_delta") {
                  process.stdout.write(event.text);
                } else if (event.type === "phase_start") {
                  console.log(
                    `\n[pipeline] ▶ ${event.phase.toUpperCase()} (attempt ${event.attempt})`,
                  );
                } else if (event.type === "phase_end") {
                  const icon = event.success ? "✅" : "❌";
                  console.log(
                    `[pipeline] ${icon} ${event.phase.toUpperCase()} (${event.durationMs}ms)`,
                  );
                } else if (event.type === "validation_result") {
                  for (const step of event.steps) {
                    const icon = step.passed ? "✓" : "✗";
                    console.log(
                      `  ${icon} ${step.name} (${step.durationMs}ms)`,
                    );
                  }
                }
                if (db && taskId) {
                  void insertTelemetryEvent(db, {
                    taskId,
                    eventType: event.type,
                    payload: event,
                  }).catch(() => {});
                }
              },
            });

            if (result.executeSuccess) {
              // Pipeline with --pr handles commit+push internally; skip autoCommit
              if (!opts.pr) {
                autoCommit(repoPath, prompt, !!opts.noCommit);
              }
              console.log("\n✅ pipeline complete");
              if (result.prUrl) console.log(`PR: ${result.prUrl}`);
              await finalizeDb("completed", "completed");
            } else {
              console.log(
                "\n❌ pipeline failed (validation did not pass after retries)",
              );
              await finalizeDb("failed", "failed");
            }
          } catch (err: unknown) {
            console.error(
              "\n❌",
              err instanceof Error ? err.message : String(err),
            );
            await finalizeDb("failed", "failed");
          }
          return;
        }

        if (mode === "delegate") {
          // Create a feature branch unless --no-commit or already on a feature branch
          const defaultBranch = getDefaultBranch(repoPath);
          let clawBranch: string | null = null;
          if (!opts.noCommit) {
            clawBranch = createClawBranch(repoPath, prompt);
          }

          const delegateProvider = effectiveRoute.provider;
          const delegateEvents =
            delegateProvider === "opencode"
              ? runOpencodePipe({
                  prompt,
                  model: opts.model ?? config.providers.opencode.default_model,
                  opencodeBin: config.providers.opencode.binary,
                  workspacePath: repoPath,
                })
              : runClaudePipe({
                  prompt,
                  model: opts.model,
                  claudeBin: config.providers.anthropic.binary,
                  workspacePath: repoPath,
                });

          let endReason = "completed";

          try {
            for await (const event of delegateEvents) {
              // Publish to Redis SSE so the dashboard sees live events
              if (redis && taskId) {
                void publishEvent(redis, {
                  type: event.type,
                  data: { taskId, ...event },
                }).catch(() => {});
              }

              if (event.type === "text_delta") {
                process.stdout.write(event.text);
                if (db && taskId) {
                  void insertTelemetryEvent(db, {
                    taskId,
                    eventType: "text_delta",
                    payload: { text: event.text },
                  }).catch(() => {});
                }
              } else if (event.type === "tool_use") {
                const input = JSON.stringify(event.input ?? {});
                const preview =
                  input.length > 60 ? input.slice(0, 57) + "..." : input;
                process.stderr.write(`\n[tool] ${event.name}(${preview})\n`);
                if (db && taskId) {
                  void insertTelemetryEvent(db, {
                    taskId,
                    eventType: "tool_use",
                    payload: { name: event.name, input: event.input },
                  }).catch(() => {});
                }
              } else if (event.type === "token_update") {
                process.stderr.write(
                  `\r[tokens] ${event.used.toLocaleString()} / ${event.budget.toLocaleString()} (${event.percent}%)   `,
                );
                if (db && taskId) {
                  void insertTelemetryEvent(db, {
                    taskId,
                    eventType: "token_update",
                    payload: {
                      used: event.used,
                      budget: event.budget,
                      percent: event.percent,
                    },
                  }).catch(() => {});
                  void updateTaskTokens(db, taskId, event.used).catch(() => {});
                  if (workItemId) {
                    void rollupWorkItemTokens(db, workItemId).catch(() => {});
                  }
                }
              } else if (event.type === "session_end") {
                endReason = event.reason;
                process.stderr.write("\n");
                if (db && taskId) {
                  void insertTelemetryEvent(db, {
                    taskId,
                    eventType: "session_end",
                    payload: { reason: event.reason },
                  }).catch(() => {});
                }
                if (event.reason === "completed") {
                  console.log("\n✅ done");
                  const committed = autoCommit(
                    repoPath,
                    prompt,
                    !!opts.noCommit,
                  );
                  if (committed && clawBranch && clawBranch !== defaultBranch) {
                    pushAndCreatePr(
                      repoPath,
                      clawBranch,
                      prompt,
                      defaultBranch,
                    );
                  } else if (isGithubRepo) {
                    execSync(`git -C "${repoPath}" push origin HEAD`, {
                      stdio: "inherit",
                    });
                  }
                  if (tempDir) {
                    rmSync(tempDir, { recursive: true, force: true });
                    tempDir = null;
                  }
                } else if (event.reason === "interrupted") {
                  console.log("\n⏹  interrupted");
                } else {
                  console.log(`\n⚠️  ended: ${event.reason}`);
                }
              }
            }
          } catch (err) {
            endReason = "failed";
            console.error("\n❌", (err as Error).message);
          } finally {
            if (tempDir) {
              rmSync(tempDir, { recursive: true, force: true });
              tempDir = null;
            }
            redis?.disconnect();
          }

          const taskStatus =
            endReason === "completed"
              ? "completed"
              : endReason === "interrupted"
                ? "interrupted"
                : "failed";
          const wiStatus =
            endReason === "completed"
              ? "completed"
              : endReason === "interrupted"
                ? "interrupted"
                : "failed";
          await finalizeDb(wiStatus, taskStatus);
          // Engine mode removed — all execution is delegate (opencode or claude -p).
          // DashScope is used only for task classification (classifyTask).
        }
      },
    );
}
